#!/usr/bin/env python3
"""Turn content/blog/*.md into a SQL seed for public.posts.

Run from the repo root:

    python3 scripts/generate-post-seed.py > supabase/migrations/0002_seed_posts.sql

Idempotent by design: the generated statement upserts on slug, so re-running
the migration after editing a markdown file refreshes that row instead of
failing on the unique index.
"""

import os
import re
import sys

CONTENT_DIR = os.path.join("content", "blog")
VALID_CATEGORIES = {"Tech", "Story"}


def parse_frontmatter(text):
    """Split a post into (frontmatter dict, body).

    Deliberately not a full YAML parser — these posts only use flat
    `key: value` pairs, and pulling in PyYAML for that would add a dependency
    the repo does not otherwise need.
    """
    match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?", text, re.S)
    if not match:
        return None, text

    fields = {}
    for line in match.group(1).split("\n"):
        pair = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if not pair:
            continue
        value = pair.group(2).strip()
        # Frontmatter values are quoted inconsistently across the posts.
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        fields[pair.group(1)] = value

    return fields, text[match.end():]


def quote(value):
    """Dollar-quote, so markdown bodies full of quotes and backslashes
    survive without escaping games."""
    tag = "md"
    n = 0
    while f"${tag}$" in value:
        n += 1
        tag = f"md{n}"
    return f"${tag}${value}${tag}$"


def main():
    if not os.path.isdir(CONTENT_DIR):
        sys.exit(f"missing {CONTENT_DIR} — run this from the repo root")

    rows = []
    problems = []

    for name in sorted(os.listdir(CONTENT_DIR)):
        if not name.endswith(".md"):
            continue

        slug = name[:-3]
        raw = open(os.path.join(CONTENT_DIR, name), encoding="utf-8").read()
        fields, body = parse_frontmatter(raw)

        if fields is None:
            problems.append(f"{name}: no frontmatter")
            continue

        title = fields.get("title", "").strip()
        date = fields.get("date", "").strip()
        category = fields.get("category", "Tech").strip()

        if not title:
            problems.append(f"{name}: missing title")
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
            problems.append(f"{name}: bad date {date!r}")
        if category not in VALID_CATEGORIES:
            problems.append(f"{name}: unknown category {category!r}")

        rows.append(
            "  ({}, {}, {}, {}, {}, '{}')".format(
                quote(slug),
                quote(title),
                quote(fields.get("description", "").strip()),
                quote(category),
                quote(body.strip()),
                date,
            )
        )

    if problems:
        # Fail loudly rather than silently importing a broken post.
        sys.exit("refusing to generate seed:\n  " + "\n  ".join(problems))

    print("-- Generated by scripts/generate-post-seed.py. Do not edit by hand.")
    print(f"-- {len(rows)} posts imported from content/blog/.")
    print()
    print("insert into public.posts")
    print("  (slug, title, description, category, content, published_at)")
    print("values")
    print(",\n".join(rows))
    print("on conflict (slug) do update set")
    print("  title       = excluded.title,")
    print("  description = excluded.description,")
    print("  category    = excluded.category,")
    print("  content     = excluded.content,")
    print("  published_at = excluded.published_at;")


if __name__ == "__main__":
    main()
